name: velik
description: "A fun virtual cycling playground."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.34.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/parallax/
